/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.9, using .NET Server 3.3.0 template (version 0)
**
**     This is a template file that was generated for your convenience.
**     This file will not be overwritten when generating code again.
**     ADD YOUR IMPLEMTATION HERE!
** </auto-generated>
**
** Copyright (c) 2006-2023 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://opcfoundation.org/UA/DI/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using UnifiedAutomation.UaBase;
using UnifiedAutomation.UaServer;

namespace OpcUa.DI
{
    public partial class TransferServicesModel : BaseObjectModel, ITransferServicesMethods
    {
        /// <summary>
        /// https://reference.opcfoundation.org/DI/v104/docs/6.4.6
        /// </summary>
        /// <param name="context"></param>
        /// <param name="model"></param>
        /// <param name="TransferID"></param>
        /// <param name="SequenceNumber"></param>
        /// <param name="MaxParameterResultsToReturn"></param>
        /// <param name="OmitGoodResults"></param>
        /// <param name="FetchResultData">out: </param>
        /// <returns></returns>
        public StatusCode FetchTransferResultData(
            RequestContext context,
            TransferServicesModel model,
            int TransferID,
            int SequenceNumber,
            int MaxParameterResultsToReturn,
            bool OmitGoodResults,
            out ExtensionObject FetchResultData
            )
        {
            FetchResultData = null;
            return StatusCodes.BadNotImplemented;
        }

        /// <summary>
        /// https://reference.opcfoundation.org/DI/v104/docs/6.4.5
        /// </summary>
        /// <param name="context"></param>
        /// <param name="model"></param>
        /// <param name="TransferID">out: </param>
        /// <param name="InitTransferStatus">out: </param>
        /// <returns></returns>
        public StatusCode TransferFromDevice(
            RequestContext context,
            TransferServicesModel model,
            out int TransferID,
            out int InitTransferStatus
            )
        {
            TransferID = (int)0;
            InitTransferStatus = (int)0;
            return StatusCodes.BadNotImplemented;
        }

        /// <summary>
        /// https://reference.opcfoundation.org/DI/v104/docs/6.4.4
        /// </summary>
        /// <param name="context"></param>
        /// <param name="model"></param>
        /// <param name="TransferID">out: </param>
        /// <param name="InitTransferStatus">out: </param>
        /// <returns></returns>
        public StatusCode TransferToDevice(
            RequestContext context,
            TransferServicesModel model,
            out int TransferID,
            out int InitTransferStatus
            )
        {
            TransferID = (int)0;
            InitTransferStatus = (int)0;
            return StatusCodes.BadNotImplemented;
        }

    }
}

